# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Lv CoatsOfArms.Repo.insert!(%LvCoatsOfArms.SomeModel{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will halt execution if something goes wrong.

alias LvCoatsOfArms.Repo
alias LvCoatsOfArms.City

Repo.delete_all(City)

Repo.insert!(%City{name: "Ainaži", image_path: "Ainaži.png"})
Repo.insert!(%City{name: "Aizkraukle", image_path: "Aizkraukle.png"})
Repo.insert!(%City{name: "Aizpute", image_path: "Aizpute.png"})
Repo.insert!(%City{name: "Aknīste", image_path: "Aknīste.png"})
Repo.insert!(%City{name: "Aloja", image_path: "Aloja.png"})
Repo.insert!(%City{name: "Alūksne", image_path: "Alūksne.png"})
Repo.insert!(%City{name: "Ape", image_path: "Ape.png"})
Repo.insert!(%City{name: "Auce", image_path: "Auce.png"})
Repo.insert!(%City{name: "Baldone", image_path: "Baldone.png"})
Repo.insert!(%City{name: "Baloži", image_path: "Baloži.png"})
Repo.insert!(%City{name: "Balvi", image_path: "Balvi.png"})
Repo.insert!(%City{name: "Bauska", image_path: "Bauska.png"})
Repo.insert!(%City{name: "Brocēni", image_path: "Brocēni.png"})
Repo.insert!(%City{name: "Cēsis", image_path: "Cēsis.png"})
Repo.insert!(%City{name: "Cesvaine", image_path: "Cesvaine.png"})
Repo.insert!(%City{name: "Dagda", image_path: "Dagda.png"})
Repo.insert!(%City{name: "Daugavpils", image_path: "Daugavpils.png"})
Repo.insert!(%City{name: "Dobele", image_path: "Dobele.png"})
Repo.insert!(%City{name: "Durbe", image_path: "Durbe.png"})
Repo.insert!(%City{name: "Grobiņa", image_path: "Grobiņa.png"})
Repo.insert!(%City{name: "Gulbene", image_path: "Gulbene.png"})
Repo.insert!(%City{name: "Ikšķile", image_path: "Ikšķile.png"})
Repo.insert!(%City{name: "Ilūkste", image_path: "Ilūkste.png"})
Repo.insert!(%City{name: "Jaunjelgava", image_path: "Jaunjelgava.png"})
Repo.insert!(%City{name: "Jēkabpils", image_path: "Jēkabpils.png"})
Repo.insert!(%City{name: "Jelgava", image_path: "Jelgava.png"})
Repo.insert!(%City{name: "Jūrmala", image_path: "Jūrmala.png"})
Repo.insert!(%City{name: "Kandava", image_path: "Kandava.png"})
Repo.insert!(%City{name: "Kārsava", image_path: "Kārsava.png"})
Repo.insert!(%City{name: "Krāslava", image_path: "Krāslava.png"})
Repo.insert!(%City{name: "Kuldīga", image_path: "Kuldīga.png"})
Repo.insert!(%City{name: "Ķegums", image_path: "Ķegums.png"})
Repo.insert!(%City{name: "Lielvārde", image_path: "Lielvārde.png"})
Repo.insert!(%City{name: "Liepāja", image_path: "Liepāja.png"})
Repo.insert!(%City{name: "Līgatne", image_path: "Līgatne.png"})
Repo.insert!(%City{name: "Limbaži", image_path: "Limbaži.png"})
Repo.insert!(%City{name: "Līvāni", image_path: "Līvāni.png"})
Repo.insert!(%City{name: "Lubāna", image_path: "Lubāna.png"})
Repo.insert!(%City{name: "Ludza", image_path: "Ludza.png"})
Repo.insert!(%City{name: "Madona", image_path: "Madona.png"})
Repo.insert!(%City{name: "Mazsalaca", image_path: "Mazsalaca.png"})
Repo.insert!(%City{name: "Ogre", image_path: "Ogre.png"})
Repo.insert!(%City{name: "Olaine", image_path: "Olaine.png"})
Repo.insert!(%City{name: "Pāvilosta", image_path: "Pāvilosta.png"})
Repo.insert!(%City{name: "Piltene", image_path: "Piltene.png"})
Repo.insert!(%City{name: "Pļaviņas", image_path: "Pļaviņas.png"})
Repo.insert!(%City{name: "Preiļi", image_path: "Preiļi.png"})
Repo.insert!(%City{name: "Priekule", image_path: "Priekule.png"})
Repo.insert!(%City{name: "Rēzekne", image_path: "Rēzekne.png"})
Repo.insert!(%City{name: "Riga", image_path: "Riga.png"})
Repo.insert!(%City{name: "Rūjiena", image_path: "Rūjiena.png"})
Repo.insert!(%City{name: "Sabile", image_path: "Sabile.png"})
Repo.insert!(%City{name: "Salacgrīva", image_path: "Salacgrīva.png"})
Repo.insert!(%City{name: "Salaspils", image_path: "Salaspils.png"})
Repo.insert!(%City{name: "Saldus", image_path: "Saldus.png"})
Repo.insert!(%City{name: "Saulkrasti", image_path: "Saulkrasti.png"})
Repo.insert!(%City{name: "Seda", image_path: "Seda.png"})
Repo.insert!(%City{name: "Sigulda", image_path: "Sigulda.png"})
Repo.insert!(%City{name: "Skrunda", image_path: "Skrunda.png"})
Repo.insert!(%City{name: "Smiltene", image_path: "Smiltene.png"})
Repo.insert!(%City{name: "Staicele", image_path: "Staicele.png"})
Repo.insert!(%City{name: "Stende", image_path: "Stende.png"})
Repo.insert!(%City{name: "Strenči", image_path: "Strenči.png"})
Repo.insert!(%City{name: "Subate", image_path: "Subate.png"})
Repo.insert!(%City{name: "Talsi", image_path: "Talsi.png"})
Repo.insert!(%City{name: "Tukums", image_path: "Tukums.png"})
Repo.insert!(%City{name: "Valdemārpils", image_path: "Valdemārpils.png"})
Repo.insert!(%City{name: "Valka", image_path: "Valka.png"})
Repo.insert!(%City{name: "Valmiera", image_path: "Valmiera.png"})
Repo.insert!(%City{name: "Vangaži", image_path: "Vangaži.png"})
Repo.insert!(%City{name: "Varakļāni", image_path: "Varakļāni.png"})
Repo.insert!(%City{name: "Ventspils", image_path: "Ventspils.png"})
Repo.insert!(%City{name: "Viesīte", image_path: "Viesīte.png"})
Repo.insert!(%City{name: "Viļaka", image_path: "Viļaka.png"})
Repo.insert!(%City{name: "Viļāni", image_path: "Viļāni.png"})
Repo.insert!(%City{name: "Zilupe", image_path: "Zilupe.png"})
