# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Lv CoatsOfArms.Repo.insert!(%LvCoatsOfArms.SomeModel{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will halt execution if something goes wrong.

alias LvCoatsOfArms.Repo
alias LvCoatsOfArms.City
alias LvCoatsOfArms.County

Repo.delete_all(City)
Repo.delete_all(County)

Repo.insert!(%City{name: "Ainaži", image_path: "Ainazi.png"})
Repo.insert!(%City{name: "Aizkraukle", image_path: "Aizkraukle.png"})
Repo.insert!(%City{name: "Aizpute", image_path: "Aizpute.png"})
Repo.insert!(%City{name: "Aknīste", image_path: "Akniste.png"})
Repo.insert!(%City{name: "Aloja", image_path: "Aloja.png"})
Repo.insert!(%City{name: "Alūksne", image_path: "Aluksne.png"})
Repo.insert!(%City{name: "Ape", image_path: "Ape.png"})
Repo.insert!(%City{name: "Auce", image_path: "Auce.png"})
Repo.insert!(%City{name: "Baldone", image_path: "Baldone.png"})
Repo.insert!(%City{name: "Baloži", image_path: "Balozi.png"})
Repo.insert!(%City{name: "Balvi", image_path: "Balvi.png"})
Repo.insert!(%City{name: "Bauska", image_path: "Bauska.png"})
Repo.insert!(%City{name: "Brocēni", image_path: "Broceni.png"})
Repo.insert!(%City{name: "Cēsis", image_path: "Cesis.png"})
Repo.insert!(%City{name: "Cesvaine", image_path: "Cesvaine.png"})
Repo.insert!(%City{name: "Dagda", image_path: "Dagda.png"})
Repo.insert!(%City{name: "Daugavpils", image_path: "Daugavpils.png"})
Repo.insert!(%City{name: "Dobele", image_path: "Dobele.png"})
Repo.insert!(%City{name: "Durbe", image_path: "Durbe.png"})
Repo.insert!(%City{name: "Grobiņa", image_path: "Grobina.png"})
Repo.insert!(%City{name: "Gulbene", image_path: "Gulbene.png"})
Repo.insert!(%City{name: "Ikšķile", image_path: "Ikskile.png"})
Repo.insert!(%City{name: "Ilūkste", image_path: "Ilukste.png"})
Repo.insert!(%City{name: "Jaunjelgava", image_path: "Jaunjelgava.png"})
Repo.insert!(%City{name: "Jēkabpils", image_path: "Jekabpils.png"})
Repo.insert!(%City{name: "Jelgava", image_path: "Jelgava.png"})
Repo.insert!(%City{name: "Jūrmala", image_path: "Jurmala.png"})
Repo.insert!(%City{name: "Kandava", image_path: "Kandava.png"})
Repo.insert!(%City{name: "Kārsava", image_path: "Karsava.png"})
Repo.insert!(%City{name: "Krāslava", image_path: "Kegums.png"})
Repo.insert!(%City{name: "Kuldīga", image_path: "Kraslava.png"})
Repo.insert!(%City{name: "Ķegums", image_path: "Kuldiga.png"})
Repo.insert!(%City{name: "Lielvārde", image_path: "Lielvarde.png"})
Repo.insert!(%City{name: "Liepāja", image_path: "Liepaja.png"})
Repo.insert!(%City{name: "Līgatne", image_path: "Ligatne.png"})
Repo.insert!(%City{name: "Limbaži", image_path: "Limbazi.png"})
Repo.insert!(%City{name: "Līvāni", image_path: "Livani.png"})
Repo.insert!(%City{name: "Lubāna", image_path: "Lubana.png"})
Repo.insert!(%City{name: "Ludza", image_path: "Ludza.png"})
Repo.insert!(%City{name: "Madona", image_path: "Madona.png"})
Repo.insert!(%City{name: "Mazsalaca", image_path: "Mazsalaca.png"})
Repo.insert!(%City{name: "Ogre", image_path: "Ogre.png"})
Repo.insert!(%City{name: "Olaine", image_path: "Olaine.png"})
Repo.insert!(%City{name: "Pāvilosta", image_path: "Pavilosta.png"})
Repo.insert!(%City{name: "Piltene", image_path: "Piltene.png"})
Repo.insert!(%City{name: "Pļaviņas", image_path: "Plavinas.png"})
Repo.insert!(%City{name: "Preiļi", image_path: "Preili.png"})
Repo.insert!(%City{name: "Priekule", image_path: "Priekule.png"})
Repo.insert!(%City{name: "Rēzekne", image_path: "Rezekne.png"})
Repo.insert!(%City{name: "Riga", image_path: "Riga.png"})
Repo.insert!(%City{name: "Rūjiena", image_path: "Rujiena.png"})
Repo.insert!(%City{name: "Sabile", image_path: "Sabile.png"})
Repo.insert!(%City{name: "Salacgrīva", image_path: "Salacgriva.png"})
Repo.insert!(%City{name: "Salaspils", image_path: "Salaspils.png"})
Repo.insert!(%City{name: "Saldus", image_path: "Saldus.png"})
Repo.insert!(%City{name: "Saulkrasti", image_path: "Saulkrasti.png"})
Repo.insert!(%City{name: "Seda", image_path: "Seda.png"})
Repo.insert!(%City{name: "Sigulda", image_path: "Sigulda.png"})
Repo.insert!(%City{name: "Skrunda", image_path: "Skrunda.png"})
Repo.insert!(%City{name: "Smiltene", image_path: "Smiltene.png"})
Repo.insert!(%City{name: "Staicele", image_path: "Staicele.png"})
Repo.insert!(%City{name: "Stende", image_path: "Stende.png"})
Repo.insert!(%City{name: "Strenči", image_path: "Strenci.png"})
Repo.insert!(%City{name: "Subate", image_path: "Subate.png"})
Repo.insert!(%City{name: "Talsi", image_path: "Talsi.png"})
Repo.insert!(%City{name: "Tukums", image_path: "Tukums.png"})
Repo.insert!(%City{name: "Valdemārpils", image_path: "Valdemarpils.png"})
Repo.insert!(%City{name: "Valka", image_path: "Valka.png"})
Repo.insert!(%City{name: "Valmiera", image_path: "Valmiera.png"})
Repo.insert!(%City{name: "Vangaži", image_path: "Vangazi.png"})
Repo.insert!(%City{name: "Varakļāni", image_path: "Varaklani.png"})
Repo.insert!(%City{name: "Ventspils", image_path: "Ventspils.png"})
Repo.insert!(%City{name: "Viesīte", image_path: "Viesite.png"})
Repo.insert!(%City{name: "Viļaka", image_path: "Vilaka.png"})
Repo.insert!(%City{name: "Viļāni", image_path: "Vilani.png"})
Repo.insert!(%City{name: "Zilupe", image_path: "Zilupe.png"})

Repo.insert!(%County{name: "Aglonas novads", image_path: "Aglonas novads.png"})
Repo.insert!(%County{name: "Aizkraukles novads", image_path: "Aizkraukles novads.png"})
Repo.insert!(%County{name: "Aizputes novads", image_path: "Aizputes novads.png"})
Repo.insert!(%County{name: "Aknīstes novads", image_path: "Aknistes novads.png"})
Repo.insert!(%County{name: "Alojas novads", image_path: "Alojas novads.png"})
Repo.insert!(%County{name: "Alsungas novads", image_path: "Alsungas novads.png"})
Repo.insert!(%County{name: "Alūksnes novads", image_path: "Aluksnes novads.png"})
Repo.insert!(%County{name: "Amatas novads", image_path: "Amatas novads.png"})
Repo.insert!(%County{name: "Apes novads", image_path: "Apes novads.png"})
Repo.insert!(%County{name: "Auces novads", image_path: "Auces novads.png"})
Repo.insert!(%County{name: "Babītes novads", image_path: "Babites novads.png"})
Repo.insert!(%County{name: "Baldones novads", image_path: "Baldones novads.png"})
Repo.insert!(%County{name: "Baltinavas novads", image_path: "Baltinavas novads.png"})
Repo.insert!(%County{name: "Balvu novads", image_path: "Balvu novads.png"})
Repo.insert!(%County{name: "Bauskas novads", image_path: "Bauskas novads.png"})
Repo.insert!(%County{name: "Beverīnas novads", image_path: "Beverinas novads.png"})
Repo.insert!(%County{name: "Brocēnu novads", image_path: "Brocenu novads.png"})
Repo.insert!(%County{name: "Burtnieku novads", image_path: "Burtnieku novads.png"})
Repo.insert!(%County{name: "Carnikavas novads", image_path: "Carnikavas novads.png"})
Repo.insert!(%County{name: "Cesvaines novads", image_path: "Cesvaines novads.png"})
Repo.insert!(%County{name: "Ciblas novads", image_path: "Ciblas novads.png"})
Repo.insert!(%County{name: "Cēsu novads", image_path: "Cesu novads.png"})
Repo.insert!(%County{name: "Dagdas novads", image_path: "Dagdas novads.png"})
Repo.insert!(%County{name: "Daugavpils novads", image_path: "Daugavpils novads.png"})
Repo.insert!(%County{name: "Dobeles novads", image_path: "Dobeles novads.png"})
Repo.insert!(%County{name: "Dundagas novads", image_path: "Dundagas novads.png"})
Repo.insert!(%County{name: "Durbes novads", image_path: "Durbes novads.png"})
Repo.insert!(%County{name: "Engures novads", image_path: "Engures novads.png"})
Repo.insert!(%County{name: "Garkalnes novads", image_path: "Garkalnes novads.png"})
Repo.insert!(%County{name: "Grobiņas novads", image_path: "Grobinas novads.png"})
Repo.insert!(%County{name: "Gulbenes novads", image_path: "Gulbenes novads.png"})
Repo.insert!(%County{name: "Iecavas novads", image_path: "Iecavas novads.png"})
Repo.insert!(%County{name: "Ikšķiles novads", image_path: "Ikskiles novads.png"})
Repo.insert!(%County{name: "Ilūkstes novads", image_path: "Ilukstes novads.png"})
Repo.insert!(%County{name: "Inčukalna novads", image_path: "Incukalna novads.png"})
Repo.insert!(%County{name: "Jaunjelgavas novads", image_path: "Jaunjelgavas novads.png"})
Repo.insert!(%County{name: "Jaunpiebalgas novads", image_path: "Jaunpiebalgas novads.png"})
Repo.insert!(%County{name: "Jaunpils novads", image_path: "Jaunpils novads.png"})
Repo.insert!(%County{name: "Jelgavas novads", image_path: "Jelgavas novads.png"})
Repo.insert!(%County{name: "Jēkabpils novads", image_path: "Jekabpils novads.png"})
Repo.insert!(%County{name: "Kandavas novads", image_path: "Kandavas novads.png"})
Repo.insert!(%County{name: "Kocēnu novads", image_path: "Kocenu novads.png"})
Repo.insert!(%County{name: "Kokneses novads", image_path: "Kokneses novads.png"})
Repo.insert!(%County{name: "Krimuldas novads", image_path: "Krimuldas novads.png"})
Repo.insert!(%County{name: "Krustpils novads", image_path: "Krustpils novads.png"})
Repo.insert!(%County{name: "Krāslavas novads", image_path: "Kraslavas novads.png"})
Repo.insert!(%County{name: "Kuldīgas novads", image_path: "Kuldigas novads.png"})
Repo.insert!(%County{name: "Kārsavas novads", image_path: "Karsavas novads.png"})
Repo.insert!(%County{name: "Lielvārdes novads", image_path: "Lielvardes novads.png"})
Repo.insert!(%County{name: "Limbažu novads", image_path: "Limbazu novads.png"})
Repo.insert!(%County{name: "Lubānas novads", image_path: "Lubanas novads.png"})
Repo.insert!(%County{name: "Ludzas novads", image_path: "Ludzas novads.png"})
Repo.insert!(%County{name: "Līgatnes novads", image_path: "Ligatnes novads.png"})
Repo.insert!(%County{name: "Līvānu novads", image_path: "Livanu novads.png"})
Repo.insert!(%County{name: "Madonas novads", image_path: "Madonas novads.png"})
Repo.insert!(%County{name: "Mazsalacas novads", image_path: "Mazsalacas novads.png"})
Repo.insert!(%County{name: "Mālpils novads", image_path: "Malpils novads.png"})
Repo.insert!(%County{name: "Mērsraga novads", image_path: "Mersraga novads.png"})
Repo.insert!(%County{name: "Mārupes novads", image_path: "Marupes novads.png"})
Repo.insert!(%County{name: "Naukšēnu novads", image_path: "Nauksenu novads.png"})
Repo.insert!(%County{name: "Neretas novads", image_path: "Neretas novads.png"})
Repo.insert!(%County{name: "Nīcas novads", image_path: "Nicas novads.png"})
Repo.insert!(%County{name: "Ogres novads", image_path: "Ogres novads.png"})
Repo.insert!(%County{name: "Olaines novads", image_path: "Olaines novads.png"})
Repo.insert!(%County{name: "Ozolnieku novads", image_path: "Ozolnieku novads.png"})
Repo.insert!(%County{name: "Preiļu novads", image_path: "Preilu novads.png"})
Repo.insert!(%County{name: "Priekules novads", image_path: "Priekules novads.png"})
Repo.insert!(%County{name: "Priekuļu novads", image_path: "Priekulu novads.png"})
Repo.insert!(%County{name: "Pļaviņu novads", image_path: "Plavinu novads.png"})
Repo.insert!(%County{name: "Pārgaujas novads", image_path: "Pargaujas novads.png"})
Repo.insert!(%County{name: "Pāvilostas novads", image_path: "Pavilostas novads.png"})
Repo.insert!(%County{name: "Raunas novads", image_path: "Raunas novads.png"})
Repo.insert!(%County{name: "Rēzeknes novads", image_path: "Riebinu novads.png"})
Repo.insert!(%County{name: "Riebiņu novads", image_path: "Rojas novads.png"})
Repo.insert!(%County{name: "Rojas novads", image_path: "Ropazu novads.png"})
Repo.insert!(%County{name: "Ropažu novads", image_path: "Rucavas novads.png"})
Repo.insert!(%County{name: "Rucavas novads", image_path: "Rugaju novads.png"})
Repo.insert!(%County{name: "Rugāju novads", image_path: "Rundales novads.png"})
Repo.insert!(%County{name: "Rundāles novads", image_path: "Rujienas novads.png"})
Repo.insert!(%County{name: "Rūjienas novads", image_path: "Rezeknes novads.png"})
Repo.insert!(%County{name: "Salacgrīvas novads", image_path: "Salacgrivas novads.png"})
Repo.insert!(%County{name: "Salas novads", image_path: "Salas novads.png"})
Repo.insert!(%County{name: "Salaspils novads", image_path: "Salaspils novads.png"})
Repo.insert!(%County{name: "Saldus novads", image_path: "Saldus novads.png"})
Repo.insert!(%County{name: "Saulkrastu novads", image_path: "Saulkrastu novads.png"})
Repo.insert!(%County{name: "Siguldas novads", image_path: "Siguldas novads.png"})
Repo.insert!(%County{name: "Skrundas novads", image_path: "Skrundas novads.png"})
Repo.insert!(%County{name: "Skrīveru novads", image_path: "Skriveru novads.png"})
Repo.insert!(%County{name: "Smiltenes novads", image_path: "Smiltenes novads.png"})
Repo.insert!(%County{name: "Stopiņu novads", image_path: "Stopinu novads.png"})
Repo.insert!(%County{name: "Strenču novads", image_path: "Strencu novads.png"})
Repo.insert!(%County{name: "Sējas novads", image_path: "Sejas novads.png"})
Repo.insert!(%County{name: "Talsu novads", image_path: "Talsu novads.png"})
Repo.insert!(%County{name: "Tukuma novads", image_path: "Tukuma novads.png"})
Repo.insert!(%County{name: "Tērvetes novads", image_path: "Tervetes novads.png"})
Repo.insert!(%County{name: "Vaiņodes novads", image_path: "Vainodes novads.png"})
Repo.insert!(%County{name: "Valkas novads", image_path: "Valkas novads.png"})
Repo.insert!(%County{name: "Varakļānu novads", image_path: "Varaklanu novads.png"})
Repo.insert!(%County{name: "Vecpiebalgas novads", image_path: "Vecpiebalgas novads.png"})
Repo.insert!(%County{name: "Vecumnieku novads", image_path: "Vecumnieku novads.png"})
Repo.insert!(%County{name: "Ventspils novads", image_path: "Ventspils novads.png"})
Repo.insert!(%County{name: "Viesītes novads", image_path: "Viesites novads.png"})
Repo.insert!(%County{name: "Viļakas novads", image_path: "Vilakas novads.png"})
Repo.insert!(%County{name: "Viļānu novads", image_path: "Vilanu novads.png"})
Repo.insert!(%County{name: "Vārkavas novads", image_path: "Varkavas novads.png"})
Repo.insert!(%County{name: "Zilupes novads", image_path: "Zilupes novads.png"})
Repo.insert!(%County{name: "Ādažu novads", image_path: "Adazu novads.png"})
Repo.insert!(%County{name: "Ķeguma novads", image_path: "Keguma novads.png"})
Repo.insert!(%County{name: "Ķekavas novads", image_path: "Kekavas novads.png"})
Repo.insert!(%County{name: "Ērgļu novads", image_path: "Erglu novads.png"})
